services:
  robijnsbos_webserver:
    container_name: robijnsbos_backend
    hostname: robijnsbos.home
    build:
      context: ./web-app
      dockerfile: docker/robijnsbos.dockerfile
    tty: true
    environment:
      TZ: Europe/Amsterdam
      SERVICE_NAME: robijnsbos
      SERVICE_TAGS: dev
    working_dir: /var/www/
    volumes:
      - ./web-app:/var/www/
    networks:
      - robijnsbos_network
    ports:
      - "12011:80"
  robijnsbos_mariadb:
    container_name: robijnsbos_mariadb
    image: "mariadb:latest"
    ports:
      - "12012:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "robijnsbos"
      MYSQL_USER: "robijnsbos"
      MYSQL_PASSWORD: "secret"
    networks:
      - robijnsbos_network
  robijnsbos_npm:
    container_name: robijnsbos_npm
    image: node:current-alpine
    volumes:
      - ./web-app:/var/www
    entrypoint: [ "npm", "run", "dev" ]
    working_dir: /var/www/
    ports:
      - "12013:12013"
    networks:
      - robijnsbos_network
networks:
  robijnsbos_network:
    driver: bridge
